# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cSi1HS-uz-rll5T0MvuJTpuLgd6VG1Cb
"""

# Function to extract entities from text
def extract_entities_from_text(text, label):
    entities = []
    lines = text.split('\n')
    for line in lines:
        if line.strip():  # Ignore empty lines
            entities.append({"Entity": line.strip(), "Label": label})
    return entities

# Read data from the dataset file
file_path = "/content/FLAT_RCL.txt"  # Replace with the actual file path
with open(file_path, 'r') as file:
    data = file.read()

# Define columns to extract entities from
columns_to_extract = ['DESC_DEFECT', 'CONEQUENCE_DEFECT', 'CORRECTIVE_ACTION', 'NOTES']

# Extract entities from each column
all_entities = []
for column in columns_to_extract:
    column_label = column.replace('_', ' ').title()  # Convert column name to title case for label
    entities = extract_entities_from_text(data, column_label)
    all_entities.extend(entities)

# Output the extracted entities
for entity in all_entities:
    print(entity)